# Python Programming Assignment 8

1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?


In [26]:
# ques 1
import numpy as np

a1 = np.matrix('1,2,3;4,5,6;7,8,9')
a2 = np.matrix('3,4,5;8,9,10;4,2,3')

print(a1)
print()
print('     +')
print()
print(a2)
print()
print('     =')
print()
print(a1+a2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

     +

[[ 3  4  5]
 [ 8  9 10]
 [ 4  2  3]]

     =

[[ 4  6  8]
 [12 14 16]
 [11 10 12]]


In [25]:
# ques 2
print(a1)
print()
print('     *')
print()
print(a2)
print()
print('     =')
print()
print(a1*a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

     *

[[ 3  4  5]
 [ 8  9 10]
 [ 4  2  3]]

     =

[[ 31  28  34]
 [ 76  73  88]
 [121 118 142]]


In [32]:
# ques 3
print(f'Original  matrix')
print(a1)
print()
print('Transpose of matrix')
print(a1.transpose())

Original  matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [53]:
# ques 4
def sorting(letter):
  l =  sorted(letter)
  return ''.join(l)

S = 'shubham'
print(f'original letter = {S}')
print()
print(f'sorted letter  = {sorting(S)}')  



original letter = shubham

sorted letter  = abhhmsu


In [55]:
# ques 5

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, how are ---you $% today."
s = ''
for i in my_str:
  if i not in punctuations:
    s += i
print(s)    



Hello how are you  today
